[workspace]
channels = ["conda-forge"]
name = "Decoding_Neural_Dynamics_of_Visual_Perceptual_Segmentation"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
# Task to register the Jupyter kernel after installation
# It runs 'python -m ipykernel install ...' inside the pixi environment
register-kernel = "python -m ipykernel install --user --name=pixi-decode-dynamics --display-name=\"Pixi (Decode Dynamics)\""

# A more comprehensive setup task (can chain commands)
# This first ensures install, then registers the kernel.
# Note: 'pixi run' implicitly runs 'pixi install' if needed, but being explicit can be clearer.
setup = "pixi install && pixi run register-kernel"

serve = "jupyter lab"

# now please run 'pixi run setup'

[dependencies]
python = ">=3.9,<3.14"
jupyterlab = ">=4.4.0,<5"
ipykernel = ">=6.29.5,<7"
imageio = ">=2.37.0,<3"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.1,<4"
pandas = ">=2.2.3,<3"
tensorboard = ">=2.19.0,<3"
gdown = ">=5.2.0,<6"
h5py = ">=3.13.0,<4"
numpy = "<2.0"

[pypi-dependencies]
pysaliency = ">=0.2.22, <0.3"
torchvision = ">=0.21.0, <0.22"
lmdb = ">=1.6.2, <2"
torchmetrics = ">=1.7.1, <2"
xformers = "*"
