[workspace]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "Decoding_Neural_Dynamics_of_Visual_Perceptual_Segmentation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# Register the Jupyter kernel after env install
register-kernel = "python -m ipykernel install --user --name=pixi-decode-dynamics --display-name=\"Pixi (Decode Dynamics)\""

# Install GPU-enabled PyTorch, TorchVision, and xformers via pip
install-gpu-packages = "python -m pip install --force-reinstall torch==2.6.0+cu118 torchvision==0.21.0+cu118 xformers --index-url https://download.pytorch.org/whl/cu118"

# Full setup: conda deps, then GPU pip packages, then register kernel
setup = "pixi install && pixi run install-gpu-packages && pixi run register-kernel"

serve = "jupyter lab"

# now please run 'pixi run setup'

[dependencies]
python        = ">=3.9,<3.14"
jupyterlab    = ">=4.4.0,<5"
ipykernel     = ">=6.29.5,<7"
imageio       = ">=2.37.0,<3"
scikit-learn  = ">=1.6.1,<2"
matplotlib    = ">=3.10.1,<4"
pandas        = ">=2.2.3,<3"
tensorboard   = ">=2.19.0,<3"
gdown         = ">=5.2.0,<6"
h5py          = ">=3.13.0,<4"
numpy         = "<2.0"
torchmetrics  = ">=1.7.1,<2"

# Conda‑managed PyTorch stack (will be overridden by GPU pip installs)
torchaudio    = ">=2.2,<3"
torchvision   = ">=0.21.0,<0.22"
pip           = ">=25.0.1,<26"

[pypi-dependencies]
# Pure‑Python packages via pip
pysaliency    = ">=0.2.22,<0.3"
lmdb          = ">=1.6.2,<2"
xformers      = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu118"]
