[workspace]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "Decoding_Neural_Dynamics_of_Visual_Perceptual_Segmentation"
platforms = ["linux-64"]
version = "1.0"

[tasks]
# Register the Jupyter kernel after env install
register-kernel = "python -m ipykernel install --user --name=pixi-decode-dynamics --display-name=\"Pixi (Decode Dynamics)\""

# Install GPU-enabled PyTorch, TorchVision, and xformers via pip
install-gpu-packages = "python -m pip install --force-reinstall torch==2.6.0+cu118 torchvision==0.21.0+cu118 xformers --index-url https://download.pytorch.org/whl/cu118"
install-pyg-packages = "python -m pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-2.6.0+cu118.html"
pysaliency-dev = { cmd = "pip install --force-reinstall git+https://github.com/matthias-k/pysaliency.git@dev" }


# Full setup: conda deps, then GPU pip packages, then register kernel
setup = "pixi install && pixi run install-gpu-packages && pixi run install-pyg-packages && pixi run pysaliency-dev && pixi run register-kernel"

serve = "jupyter lab"

# run 'pixi run setup'

[dependencies]
#python = "3.11.*"
jupyterlab    = ">=4.4.0,<5"
ipykernel     = ">=6.29.5,<7"
imageio       = ">=2.37.0,<3"
scikit-learn  = ">=1.6.1,<2"
matplotlib    = ">=3.10.1,<4"
#pandas = ">=2.2,<3"
tensorboard   = ">=2.19.0,<3"
gdown         = ">=5.2.0,<6"
h5py          = ">=3.13.0,<4"
#numpy         = "1.26.*"
torchmetrics  = ">=1.7.1,<2"

# Conda‑managed PyTorch stack (will be overridden by GPU pip installs)
torchaudio    = ">=2.2,<3"
torchvision   = ">=0.21.0,<0.22"
pip           = ">=25.0.1,<26"
octave = ">=9.4.0,<10"
gcc_linux-64 = ">=14.2.0,<15"
gxx_linux-64 = ">=14.2.0,<15"
gfortran_linux-64 = ">=14.2.0,<15"
make = ">=4.4.1,<5"
transformers = ">=4.51.3,<5"
python-dotenv = ">=1.1.0,<2"
pyyaml = ">=6.0.2,<7"
cloudpickle = ">=3.1.1,<4"
ipywidgets = ">=8.1.7,<9"
umap-learn = ">=0.5.9.post2,<0.6"
ipympl = ">=0.9.7,<0.10"

[pypi-dependencies]
lmdb          = ">=1.6.2,<2"
xformers      = "*"
opencv-python = ">=4.11.0.86, <5"
#cloudpickle   = "*"
#optree        = ">=0.13"

[pypi-options]
index-url = "https://pypi.org/simple"

extra-index-urls = [
    "https://download.pytorch.org/whl/cu118",
#    "https://data.pyg.org/whl/torch-2.6.0+cu118.html"
]

