# salicon_spade_k16_config.yaml, for train_deepgaze_spade

# --- Experiment Configuration ---
stage: 'salicon_pretrain_densenet_spade'
densenet_model_name: 'densenet201'

# --- SPADE Specific Arguments ---
segmentation_mask_dir: './masks/' 
train_mask_subdir_name: './train/'
val_mask_subdir_name: 'val'     
segmentation_mask_format: 'png'  
num_total_segments: 16
seg_embedding_dim: 64            

# --- Training Hyperparameters ---
batch_size: 8
gradient_accumulation_steps: 1   
lr: 0.0005 # 5e-4
lr_milestones: [15, 30, 45]       
min_lr: 0.0000001                 
fold: null
validation_epochs: 1              
resume_checkpoint: null

# --- Dataloading & System ---
num_workers: 8 # 8 for each gpu
train_dir: './experiments/densenet_spade'
dataset_dir: './data/pysaliency_datasets'
lmdb_dir: './data/lmdb_cache_densenet'
use_lmdb_images: false                  
cache_segmentation_masks: true        

# --- Model Generic Arguments ---
add_sa_head: false                      